# Generated by Django 4.2.8 on 2023-12-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstatePricePredictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atico', models.FloatField()),
                ('tipo_construccion', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('roomNumber', models.FloatField()),
                ('bathNumber', models.FloatField()),
                ('hasParking', models.FloatField()),
                ('hasGarden', models.FloatField()),
                ('hasSwimmingPool', models.FloatField()),
                ('hasTerrace', models.FloatField()),
                ('superficie_min', models.FloatField()),
                ('armarios_empotrados', models.FloatField()),
                ('trastero', models.FloatField()),
                ('parcela', models.FloatField()),
                ('balcon', models.FloatField()),
                ('altura', models.FloatField()),
                ('ubicacion_1', models.FloatField()),
                ('ubicacion_2', models.FloatField()),
                ('ubicacion_3', models.FloatField()),
                ('ubicacion_4', models.FloatField()),
                ('url_zona', models.CharField(blank=True, max_length=255, null=True)),
                ('isNewDevelopment', models.FloatField()),
                ('isNeedsRenovating', models.FloatField()),
                ('isGoodCondition', models.FloatField()),
            ],
        ),
    ]
