# Generated by Django 4.1.4 on 2024-01-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealEstateListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atico", models.FloatField()),
                ("tipo_construccion", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("roomNumber", models.FloatField()),
                ("bathNumber", models.FloatField()),
                ("hasParking", models.FloatField()),
                ("hasGarden", models.FloatField()),
                ("hasSwimmingPool", models.FloatField()),
                ("hasTerrace", models.FloatField()),
                ("superficie_min", models.FloatField()),
                ("armarios_empotrados", models.FloatField()),
                ("trastero", models.FloatField()),
                ("parcela", models.FloatField()),
                ("balcon", models.FloatField()),
                ("altura", models.FloatField()),
                ("ubicacion_1", models.FloatField()),
                ("ubicacion_2", models.FloatField()),
                ("ubicacion_3", models.FloatField()),
                ("ubicacion_4", models.FloatField()),
                ("url_zona", models.CharField(blank=True, max_length=255, null=True)),
                ("isNewDevelopment", models.FloatField()),
                ("isNeedsRenovating", models.FloatField()),
                ("isGoodCondition", models.FloatField()),
                ("price", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="RealEstatePricePredictor",
        ),
    ]
