# Generated by Django 4.1.4 on 2024-01-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml_app", "0002_realestatelisting_delete_realestatepricepredictor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestatelisting",
            name="ubicacion_4",
        ),
        migrations.AlterField(
            model_name="realestatelisting",
            name="ubicacion_3",
            field=models.FloatField(default=0),
        ),
    ]
