# Generated by Django 4.1.4 on 2024-01-14 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ml_app", "0003_remove_realestatelisting_ubicacion_4_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestatelisting",
            name="url_zona",
        ),
    ]
