# Generated by Django 4.1.4 on 2024-01-14 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ml_app", "0004_remove_realestatelisting_url_zona"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestatelisting",
            name="tipo_construccion",
        ),
    ]
